/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */
import { createQuery } from '@tanstack/svelte-query';
import type {
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import type { ErrorModel } from '../../models';

import { customFetch } from '../../mutators/custom-fetch.ts';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getPingUrl = () => {
  return `/ping`;
};

/**
 * Health Check
 * @summary Ping
 */
export const ping = async (options?: Parameters<typeof customFetch>[1]): Promise<string> => {
  return customFetch<string>(getPingUrl(), {
    ...options,
    method: 'GET'
  });
};

export const getPingQueryKey = () => {
  return [`/ping`] as const;
};

export const getPingQueryOptions = <
  TData = Awaited<ReturnType<typeof ping>>,
  TError = ErrorModel
>(options?: {
  query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof ping>>, TError, TData>>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPingQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof ping>>> = ({ signal }) =>
    ping({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
    Awaited<ReturnType<typeof ping>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PingQueryResult = NonNullable<Awaited<ReturnType<typeof ping>>>;
export type PingQueryError = ErrorModel;

/**
 * @summary Ping
 */

export function createPing<TData = Awaited<ReturnType<typeof ping>>, TError = ErrorModel>(
  options?: () => {
    query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof ping>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: () => QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const query = createQuery(
    () => getPingQueryOptions(options?.()),
    queryClient
  ) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query;
}

/**
 * @summary Ping
 */
export const prefetchPingQuery = async <
  TData = Awaited<ReturnType<typeof ping>>,
  TError = ErrorModel
>(
  queryClient: QueryClient,
  options?: {
    query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof ping>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  }
): Promise<QueryClient> => {
  const queryOptions = getPingQueryOptions(options);

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
};
