/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */
import { createInfiniteQuery } from '@tanstack/svelte-query';
import type {
  CreateInfiniteQueryOptions,
  CreateInfiniteQueryResult,
  DataTag,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import type {
  ErrorModel,
  PaginatedResponseSearchClassResponseItem,
  SearchClassesParams,
  SearchClassesRequest
} from '../../models';

import { customFetch } from '../../mutators/custom-fetch.ts';
import { customQueryOptions } from '../../mutators/infinite.ts';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getSearchClassesUrl = (termID: number, params?: SearchClassesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/term/${termID}/classes/search?${stringifiedParams}`
    : `/term/${termID}/classes/search`;
};

/**
 * Searches classes, with optional filtering.
 * @summary Search Classes
 */
export const searchClasses = async (
  termID: number,
  searchClassesRequest: SearchClassesRequest,
  params?: SearchClassesParams,
  options?: Parameters<typeof customFetch>[1]
): Promise<PaginatedResponseSearchClassResponseItem> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string]
        )
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return customFetch<PaginatedResponseSearchClassResponseItem>(
    getSearchClassesUrl(termID, params),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
      body: JSON.stringify(searchClassesRequest)
    }
  );
};

export const getSearchClassesInfiniteQueryKey = (
  termID: number,
  searchClassesRequest?: SearchClassesRequest,
  params?: SearchClassesParams
) => {
  return [
    'infinite',
    'POST',
    `/term/${termID}/classes/search`,
    ...(params ? [params] : []),
    searchClassesRequest
  ] as const;
};

export const useSearchClassesInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof searchClasses>>, SearchClassesParams['offset']>,
  TError = ErrorModel
>(
  termID: number,
  searchClassesRequest: SearchClassesRequest,
  params?: SearchClassesParams,
  options?: {
    query?: Partial<
      CreateInfiniteQueryOptions<
        Awaited<ReturnType<typeof searchClasses>>,
        TError,
        TData,
        QueryKey,
        SearchClassesParams['offset']
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getSearchClassesInfiniteQueryKey(termID, searchClassesRequest, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof searchClasses>>,
    QueryKey,
    SearchClassesParams['offset']
  > = ({ signal, pageParam }) =>
    searchClasses(
      termID,
      searchClassesRequest,
      { ...params, offset: pageParam ?? params?.['offset'] },
      { signal, ...requestOptions }
    );

  const customOptions = customQueryOptions({
    queryKey,
    queryFn,
    enabled: termID !== null && termID !== undefined,
    ...queryOptions
  });

  return customOptions as CreateInfiniteQueryOptions<
    Awaited<ReturnType<typeof searchClasses>>,
    TError,
    TData,
    QueryKey,
    SearchClassesParams['offset']
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SearchClassesInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchClasses>>
>;
export type SearchClassesInfiniteQueryError = ErrorModel;

/**
 * @summary Search Classes
 */

export function createSearchClassesInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof searchClasses>>, SearchClassesParams['offset']>,
  TError = ErrorModel
>(
  termID: () => number,
  searchClassesRequest: () => SearchClassesRequest,
  params?: () => SearchClassesParams,
  options?: () => {
    query?: Partial<
      CreateInfiniteQueryOptions<
        Awaited<ReturnType<typeof searchClasses>>,
        TError,
        TData,
        QueryKey,
        SearchClassesParams['offset']
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: () => QueryClient
): CreateInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const query = createInfiniteQuery(
    () =>
      useSearchClassesInfiniteQueryOptions(
        termID(),
        searchClassesRequest(),
        params?.(),
        options?.()
      ),
    queryClient
  ) as CreateInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query;
}
