/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */

export interface ClassChoice {
  /** @minItems 1 */
  class_ids: string[];
  course_id: string;
}
