/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */

export interface CustomInstructor {
  /** @nullable */
  difficulty: number | null;
  name: string;
  /** @nullable */
  rating: number | null;
  /** @nullable */
  take_again: number | null;
}
