/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */

export interface CustomMeetTime {
  /** @nullable */
  building: string | null;
  /** @nullable */
  days: string[] | null;
  /** @nullable */
  period_end: string | null;
  /** @nullable */
  period_start: string | null;
  /** @nullable */
  time_end: string | null;
  /** @nullable */
  time_start: string | null;
}
