/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */
import type { CustomBuilding } from './customBuilding.ts';
import type { CustomMeetTimeDaysItem } from './customMeetTimeDaysItem.ts';

export interface CustomMeetTime {
  building: CustomBuilding | null;
  days: CustomMeetTimeDaysItem[];
  period_end: string;
  period_start: string;
  time_end: string;
  time_start: string;
}
