/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */

export interface CustomMeetTime {
  building: string;
  days: string[];
  period_end: string;
  period_start: string;
  time_end: string;
  time_start: string;
}
