/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type CustomBuilding = {
  code: string;
  name: string;
  /** @nullable */
  room: string | null;
} | null;
