/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */

export type FilterRuleTextCourseMeetDaysField = typeof FilterRuleTextCourseMeetDaysField[keyof typeof FilterRuleTextCourseMeetDaysField];


export const FilterRuleTextCourseMeetDaysField = {
  meet_timesdays: 'meet_times.days',
} as const;
