/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */

export type FilterGlue = typeof FilterGlue[keyof typeof FilterGlue];


export const FilterGlue = {
  and: 'and',
  or: 'or',
} as const;
