/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */

export type FilterRuleTextCourseGenEdsFilter =
  (typeof FilterRuleTextCourseGenEdsFilter)[keyof typeof FilterRuleTextCourseGenEdsFilter];

export const FilterRuleTextCourseGenEdsFilter = {
  equal: 'equal',
  notEqual: 'notEqual'
} as const;
