/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */

export type FilterRuleTextCourseQuestField = typeof FilterRuleTextCourseQuestField[keyof typeof FilterRuleTextCourseQuestField];


export const FilterRuleTextCourseQuestField = {
  course_quest: 'course_quest',
} as const;
