/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */
import type { FilterRuleNumberGeneralFieldField } from './filterRuleNumberGeneralFieldField.ts';
import type { FilterRuleNumberGeneralFieldFilter } from './filterRuleNumberGeneralFieldFilter.ts';
import type { FilterRuleNumberGeneralFieldType } from './filterRuleNumberGeneralFieldType.ts';

export interface FilterRuleNumberGeneralField {
  field: FilterRuleNumberGeneralFieldField;
  filter: FilterRuleNumberGeneralFieldFilter;
  type: FilterRuleNumberGeneralFieldType;
  value: number;
}
