/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */

export type FilterRuleTimeType = typeof FilterRuleTimeType[keyof typeof FilterRuleTimeType];


export const FilterRuleTimeType = {
  time: 'time',
} as const;
