/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */
import type { FilterRuleTextGeneralFieldField } from './filterRuleTextGeneralFieldField.ts';
import type { FilterRuleTextGeneralFieldFilter } from './filterRuleTextGeneralFieldFilter.ts';
import type { FilterRuleTextGeneralFieldType } from './filterRuleTextGeneralFieldType.ts';

export interface FilterRuleTextGeneralField {
  field: FilterRuleTextGeneralFieldField;
  filter: FilterRuleTextGeneralFieldFilter;
  type: FilterRuleTextGeneralFieldType;
  value: string;
}
