/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */

export type FilterRuleTextGeneralFieldFilter =
  (typeof FilterRuleTextGeneralFieldFilter)[keyof typeof FilterRuleTextGeneralFieldFilter];

export const FilterRuleTextGeneralFieldFilter = {
  equal: 'equal',
  notEqual: 'notEqual'
} as const;
