/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */

export type FilterRuleTextCourseMeetDaysValue = typeof FilterRuleTextCourseMeetDaysValue[keyof typeof FilterRuleTextCourseMeetDaysValue];


export const FilterRuleTextCourseMeetDaysValue = {
  M: 'M',
  T: 'T',
  W: 'W',
  R: 'R',
  F: 'F',
  S: 'S',
  U: 'U',
} as const;
