/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */

export type FilterRuleTextCourseMeetDaysType =
  (typeof FilterRuleTextCourseMeetDaysType)[keyof typeof FilterRuleTextCourseMeetDaysType];

export const FilterRuleTextCourseMeetDaysType = {
  text: 'text'
} as const;
