/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */

export type FilterRuleNumberPeriodFilter =
  (typeof FilterRuleNumberPeriodFilter)[keyof typeof FilterRuleNumberPeriodFilter];

export const FilterRuleNumberPeriodFilter = {
  equal: 'equal',
  notEqual: 'notEqual',
  greater: 'greater',
  less: 'less',
  greaterOrEqual: 'greaterOrEqual',
  lessOrEqual: 'lessOrEqual'
} as const;
