/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */

export type FilterRuleNumberGeneralFieldField =
  (typeof FilterRuleNumberGeneralFieldField)[keyof typeof FilterRuleNumberGeneralFieldField];

export const FilterRuleNumberGeneralFieldField = {
  number: 'number',
  course_level: 'course_level',
  course_credits: 'course_credits',
  course_words: 'course_words',
  instructorsrating: 'instructors.rating',
  instructorsdifficulty: 'instructors.difficulty',
  instructorstake_again: 'instructors.take_again'
} as const;
