/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */

export type FilterRuleTextCourseMeetDaysFilter = typeof FilterRuleTextCourseMeetDaysFilter[keyof typeof FilterRuleTextCourseMeetDaysFilter];


export const FilterRuleTextCourseMeetDaysFilter = {
  equal: 'equal',
  notEqual: 'notEqual',
} as const;
