/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */
import type { FilterRuleTextCourseMeetDaysField } from './filterRuleTextCourseMeetDaysField.ts';
import type { FilterRuleTextCourseMeetDaysFilter } from './filterRuleTextCourseMeetDaysFilter.ts';
import type { FilterRuleTextCourseMeetDaysType } from './filterRuleTextCourseMeetDaysType.ts';
import type { FilterRuleTextCourseMeetDaysValue } from './filterRuleTextCourseMeetDaysValue.ts';

export interface FilterRuleTextCourseMeetDays {
  field: FilterRuleTextCourseMeetDaysField;
  filter: FilterRuleTextCourseMeetDaysFilter;
  type: FilterRuleTextCourseMeetDaysType;
  value: FilterRuleTextCourseMeetDaysValue;
}
