/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */

export type FilterRuleTextClassMeetTypeFilter =
  (typeof FilterRuleTextClassMeetTypeFilter)[keyof typeof FilterRuleTextClassMeetTypeFilter];

export const FilterRuleTextClassMeetTypeFilter = {
  equal: 'equal',
  notEqual: 'notEqual'
} as const;
