/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */

export type FilterRuleNumberPeriodType = typeof FilterRuleNumberPeriodType[keyof typeof FilterRuleNumberPeriodType];


export const FilterRuleNumberPeriodType = {
  number: 'number',
} as const;
