/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */

export type FilterRuleTextCourseQuestType = typeof FilterRuleTextCourseQuestType[keyof typeof FilterRuleTextCourseQuestType];


export const FilterRuleTextCourseQuestType = {
  text: 'text',
} as const;
