/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */
import type { FilterRuleTextCourseQuestField } from './filterRuleTextCourseQuestField.ts';
import type { FilterRuleTextCourseQuestFilter } from './filterRuleTextCourseQuestFilter.ts';
import type { FilterRuleTextCourseQuestType } from './filterRuleTextCourseQuestType.ts';
import type { FilterRuleTextCourseQuestValue } from './filterRuleTextCourseQuestValue.ts';

export interface FilterRuleTextCourseQuest {
  field: FilterRuleTextCourseQuestField;
  filter: FilterRuleTextCourseQuestFilter;
  type: FilterRuleTextCourseQuestType;
  value: FilterRuleTextCourseQuestValue;
}
