/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */
import type { FilterRuleTextClassMeetTypeField } from './filterRuleTextClassMeetTypeField.ts';
import type { FilterRuleTextClassMeetTypeFilter } from './filterRuleTextClassMeetTypeFilter.ts';
import type { FilterRuleTextClassMeetTypeType } from './filterRuleTextClassMeetTypeType.ts';
import type { FilterRuleTextClassMeetTypeValue } from './filterRuleTextClassMeetTypeValue.ts';

export interface FilterRuleTextClassMeetType {
  field: FilterRuleTextClassMeetTypeField;
  filter: FilterRuleTextClassMeetTypeFilter;
  type: FilterRuleTextClassMeetTypeType;
  value: FilterRuleTextClassMeetTypeValue;
}
