/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */

export type FilterRuleTextCourseGenEdsField = typeof FilterRuleTextCourseGenEdsField[keyof typeof FilterRuleTextCourseGenEdsField];


export const FilterRuleTextCourseGenEdsField = {
  course_gen_eds: 'course_gen_eds',
} as const;
