/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */

export type FilterRuleTextCourseGenEdsType =
  (typeof FilterRuleTextCourseGenEdsType)[keyof typeof FilterRuleTextCourseGenEdsType];

export const FilterRuleTextCourseGenEdsType = {
  text: 'text'
} as const;
