/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */

export type FilterRuleTextCourseQuestFilter =
  (typeof FilterRuleTextCourseQuestFilter)[keyof typeof FilterRuleTextCourseQuestFilter];

export const FilterRuleTextCourseQuestFilter = {
  equal: 'equal',
  notEqual: 'notEqual'
} as const;
