/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */
import type { FilterRuleBooleanField } from './filterRuleBooleanField.ts';
import type { FilterRuleBooleanFilter } from './filterRuleBooleanFilter.ts';
import type { FilterRuleBooleanType } from './filterRuleBooleanType.ts';

export interface FilterRuleBoolean {
  field: FilterRuleBooleanField;
  filter: FilterRuleBooleanFilter;
  type: FilterRuleBooleanType;
  value: boolean;
}
