/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */

export type FilterRuleTextClassMeetTypeField = typeof FilterRuleTextClassMeetTypeField[keyof typeof FilterRuleTextClassMeetTypeField];


export const FilterRuleTextClassMeetTypeField = {
  meet_type: 'meet_type',
} as const;
