/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */
import type { FilterRuleTextClassMeetType } from './filterRuleTextClassMeetType.ts';
import type { FilterRuleTextCourseGenEds } from './filterRuleTextCourseGenEds.ts';
import type { FilterRuleTextCourseMeetDays } from './filterRuleTextCourseMeetDays.ts';
import type { FilterRuleTextCourseQuest } from './filterRuleTextCourseQuest.ts';
import type { FilterRuleTextGeneralField } from './filterRuleTextGeneralField.ts';

export type FilterRuleText = FilterRuleTextClassMeetType | FilterRuleTextCourseGenEds | FilterRuleTextCourseQuest | FilterRuleTextCourseMeetDays | FilterRuleTextGeneralField;
