/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */

export type FilterRuleTextClassMeetTypeType =
  (typeof FilterRuleTextClassMeetTypeType)[keyof typeof FilterRuleTextClassMeetTypeType];

export const FilterRuleTextClassMeetTypeType = {
  text: 'text'
} as const;
