/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */

export type FilterRuleTextGeneralFieldType = typeof FilterRuleTextGeneralFieldType[keyof typeof FilterRuleTextGeneralFieldType];


export const FilterRuleTextGeneralFieldType = {
  text: 'text',
} as const;
