/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */

export type FilterRuleNumberGeneralFieldFilter = typeof FilterRuleNumberGeneralFieldFilter[keyof typeof FilterRuleNumberGeneralFieldFilter];


export const FilterRuleNumberGeneralFieldFilter = {
  equal: 'equal',
  notEqual: 'notEqual',
  greater: 'greater',
  less: 'less',
  greaterOrEqual: 'greaterOrEqual',
  lessOrEqual: 'lessOrEqual',
} as const;
