/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */
import type { FilterRuleNumberPeriodField } from './filterRuleNumberPeriodField.ts';
import type { FilterRuleNumberPeriodFilter } from './filterRuleNumberPeriodFilter.ts';
import type { FilterRuleNumberPeriodType } from './filterRuleNumberPeriodType.ts';
import type { FilterRuleNumberPeriodValue } from './filterRuleNumberPeriodValue.ts';

export interface FilterRuleNumberPeriod {
  field: FilterRuleNumberPeriodField;
  filter: FilterRuleNumberPeriodFilter;
  type: FilterRuleNumberPeriodType;
  value: FilterRuleNumberPeriodValue;
}
