/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */

export type FilterRuleNumberGeneralFieldType = typeof FilterRuleNumberGeneralFieldType[keyof typeof FilterRuleNumberGeneralFieldType];


export const FilterRuleNumberGeneralFieldType = {
  number: 'number',
} as const;
