/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */
import type { FilterGlue } from './filterGlue.ts';
import type { FilterRule } from './filterRule.ts';

export interface Filter {
  glue: FilterGlue;
  /** @minItems 1 */
  rules: (FilterRule | Filter)[];
}
