/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */
import type { FilterRuleBoolean } from './filterRuleBoolean.ts';
import type { FilterRuleNumber } from './filterRuleNumber.ts';
import type { FilterRuleText } from './filterRuleText.ts';
import type { FilterRuleTime } from './filterRuleTime.ts';

export type FilterRule = FilterRuleText | FilterRuleNumber | FilterRuleTime | FilterRuleBoolean;
