/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */

export type FilterRuleBooleanType =
  (typeof FilterRuleBooleanType)[keyof typeof FilterRuleBooleanType];

export const FilterRuleBooleanType = {
  boolean: 'boolean'
} as const;
