/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */

export type FilterRuleTextCourseGenEdsValue =
  (typeof FilterRuleTextCourseGenEdsValue)[keyof typeof FilterRuleTextCourseGenEdsValue];

export const FilterRuleTextCourseGenEdsValue = {
  Biological_Science: 'Biological Science',
  Physical_Science: 'Physical Science',
  Social_Science: 'Social Science',
  Mathematics: 'Mathematics',
  Composition: 'Composition',
  Humanities: 'Humanities',
  International: 'International'
} as const;
