/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */
import type { FilterRuleNumberGeneralField } from './filterRuleNumberGeneralField.ts';
import type { FilterRuleNumberPeriod } from './filterRuleNumberPeriod.ts';

export type FilterRuleNumber = FilterRuleNumberPeriod | FilterRuleNumberGeneralField;
