/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */

export type FilterRuleBooleanFilter = typeof FilterRuleBooleanFilter[keyof typeof FilterRuleBooleanFilter];


export const FilterRuleBooleanFilter = {
  equal: 'equal',
  notEqual: 'notEqual',
} as const;
