/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */
import type { FilterRuleTextCourseGenEdsField } from './filterRuleTextCourseGenEdsField.ts';
import type { FilterRuleTextCourseGenEdsFilter } from './filterRuleTextCourseGenEdsFilter.ts';
import type { FilterRuleTextCourseGenEdsType } from './filterRuleTextCourseGenEdsType.ts';
import type { FilterRuleTextCourseGenEdsValue } from './filterRuleTextCourseGenEdsValue.ts';

export interface FilterRuleTextCourseGenEds {
  field: FilterRuleTextCourseGenEdsField;
  filter: FilterRuleTextCourseGenEdsFilter;
  type: FilterRuleTextCourseGenEdsType;
  value: FilterRuleTextCourseGenEdsValue;
}
