/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */

export type FilterRuleTextGeneralFieldField = typeof FilterRuleTextGeneralFieldField[keyof typeof FilterRuleTextGeneralFieldField];


export const FilterRuleTextGeneralFieldField = {
  course_code: 'course_code',
  course_code_prefix: 'course_code_prefix',
  course_name: 'course_name',
  course_department: 'course_department',
  meet_timesbuilding: 'meet_times.building',
  instructorsname: 'instructors.name',
} as const;
