/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */

export type FilterRuleNumberPeriodValue = typeof FilterRuleNumberPeriodValue[keyof typeof FilterRuleNumberPeriodValue];


export const FilterRuleNumberPeriodValue = {
  NUMBER_1: '1',
  NUMBER_2: '2',
  NUMBER_3: '3',
  NUMBER_4: '4',
  NUMBER_5: '5',
  NUMBER_6: '6',
  NUMBER_7: '7',
  NUMBER_8: '8',
  NUMBER_9: '9',
  NUMBER_10: '10',
  NUMBER_11: '11',
  E1: 'E1',
  E2: 'E2',
  E3: 'E3',
} as const;
