/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */
import type { FilterRuleTimeField } from './filterRuleTimeField.ts';
import type { FilterRuleTimeFilter } from './filterRuleTimeFilter.ts';
import type { FilterRuleTimeType } from './filterRuleTimeType.ts';

export interface FilterRuleTime {
  field: FilterRuleTimeField;
  filter: FilterRuleTimeFilter;
  type: FilterRuleTimeType;
  value: string;
}
