/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */
import type { ClassChoice } from './classChoice.ts';
import type { GenerateSchedulesRequestDayRestrictionsItem } from './generateSchedulesRequestDayRestrictionsItem.ts';
import type { GenerateSchedulesRequestSortBy } from './generateSchedulesRequestSortBy.ts';

export interface GenerateSchedulesRequest {
  class_choices: ClassChoice[];
  day_restrictions?: GenerateSchedulesRequestDayRestrictionsItem[];
  sort_by?: GenerateSchedulesRequestSortBy;
}
