/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */

export type GenerateSchedulesParams = {
  /**
   * @minimum 0
   */
  limit?: number;
  /**
   * @minimum 0
   */
  offset?: number;
};
