/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */
import type { SearchClassResponseItem } from './searchClassResponseItem.ts';

export interface PaginatedResponseSearchClassResponseItem {
  /** @minimum 0 */
  count: number;
  /** @nullable */
  items: SearchClassResponseItem[] | null;
  /** @minimum 0 */
  limit: number;
  /** @minimum 0 */
  offset: number;
  /** @minimum 0 */
  total: number;
}
