/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */
import type { Schedule } from './schedule.ts';

export interface PaginatedResponseSchedule {
  /** @minimum 0 */
  count: number;
  items: Schedule[];
  /** @minimum 0 */
  limit: number;
  /** @minimum 0 */
  offset: number;
  /** @minimum 0 */
  total: number;
}
