/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */
import type { SelectedClass } from './selectedClass.ts';

export interface Schedule {
  classes: SelectedClass[];
}
