/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */

export type SearchClassesRequestFilterGlue =
  (typeof SearchClassesRequestFilterGlue)[keyof typeof SearchClassesRequestFilterGlue];

export const SearchClassesRequestFilterGlue = {
  and: 'and',
  or: 'or'
} as const;
