/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */
import type { Filter } from './filter.ts';
import type { FilterRule } from './filterRule.ts';
import type { SearchClassesRequestFilterGlue } from './searchClassesRequestFilterGlue.ts';

export type SearchClassesRequestFilter = {
  glue: SearchClassesRequestFilterGlue;
  /** @minItems 1 */
  rules: (FilterRule | Filter)[];
};
