/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */
import type { SearchClassesRequestFilter } from './searchClassesRequestFilter.ts';

export interface SearchClassesRequest {
  filter?: SearchClassesRequestFilter;
  /** @minLength 1 */
  search?: string;
}
