/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */
import type { TypedListClassesByIDRow } from './typedListClassesByIDRow.ts';
import type { TypedListCoursesByIDRow } from './typedListCoursesByIDRow.ts';

export interface SearchClassResponseItem {
  classes: TypedListClassesByIDRow[];
  course: TypedListCoursesByIDRow;
}
