/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */

export interface TypedListBuildingsRow {
  code: string;
  /** @nullable */
  latitude: number | null;
  /** @nullable */
  longitude: number | null;
  name: string;
}
