/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */
import type { CustomInstructor } from './customInstructor.ts';
import type { CustomMeetTime } from './customMeetTime.ts';

export interface TypedListClassesByIDRow {
  instructors: CustomInstructor[];
  meet_times: CustomMeetTime[];
  meet_type: string;
  /** @nullable */
  note: string | null;
  number: number;
}
