/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */

export interface TypedListCoursesByIDRow {
  code: string;
  credits_max: number;
  credits_min: number;
  department: string;
  description: string;
  /** @nullable */
  gen_eds: string[] | null;
  is_ai: boolean;
  is_honors: boolean;
  /** @nullable */
  is_lab: boolean | null;
  name: string;
  prerequisites: string;
  /** @nullable */
  quest: string | null;
  syllabus: string;
  words: number;
}
