/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */
import { createInfiniteQuery } from '@tanstack/svelte-query';
import type {
  CreateInfiniteQueryOptions,
  CreateInfiniteQueryResult,
  DataTag,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import type {
  ErrorModel,
  GenerateSchedulesParams,
  GenerateSchedulesRequest,
  PaginatedResponseSchedule
} from '../../models';

import { customFetch } from '../../mutators/custom-fetch.ts';
import { customQueryOptions } from '../../mutators/infinite.ts';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getGenerateSchedulesUrl = (termID: number, params?: GenerateSchedulesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/term/${termID}/schedules/generate?${stringifiedParams}`
    : `/term/${termID}/schedules/generate`;
};

/**
 * Generates schedules for provided classes.
 * @summary Generate Schedules
 */
export const generateSchedules = async (
  termID: number,
  generateSchedulesRequest: GenerateSchedulesRequest,
  params?: GenerateSchedulesParams,
  options?: Parameters<typeof customFetch>[1]
): Promise<PaginatedResponseSchedule> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string]
        )
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return customFetch<PaginatedResponseSchedule>(getGenerateSchedulesUrl(termID, params), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(generateSchedulesRequest)
  });
};

export const getGenerateSchedulesInfiniteQueryKey = (
  termID: number,
  generateSchedulesRequest?: GenerateSchedulesRequest,
  params?: GenerateSchedulesParams
) => {
  return [
    'infinite',
    'POST',
    `/term/${termID}/schedules/generate`,
    ...(params ? [params] : []),
    generateSchedulesRequest
  ] as const;
};

export const useGenerateSchedulesInfiniteQueryOptions = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof generateSchedules>>,
    GenerateSchedulesParams['offset']
  >,
  TError = ErrorModel
>(
  termID: number,
  generateSchedulesRequest: GenerateSchedulesRequest,
  params?: GenerateSchedulesParams,
  options?: {
    query?: Partial<
      CreateInfiniteQueryOptions<
        Awaited<ReturnType<typeof generateSchedules>>,
        TError,
        TData,
        QueryKey,
        GenerateSchedulesParams['offset']
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGenerateSchedulesInfiniteQueryKey(termID, generateSchedulesRequest, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof generateSchedules>>,
    QueryKey,
    GenerateSchedulesParams['offset']
  > = ({ signal, pageParam }) =>
    generateSchedules(
      termID,
      generateSchedulesRequest,
      { ...params, offset: pageParam ?? params?.['offset'] },
      { signal, ...requestOptions }
    );

  const customOptions = customQueryOptions({
    queryKey,
    queryFn,
    enabled: termID !== null && termID !== undefined,
    ...queryOptions
  });

  return customOptions as CreateInfiniteQueryOptions<
    Awaited<ReturnType<typeof generateSchedules>>,
    TError,
    TData,
    QueryKey,
    GenerateSchedulesParams['offset']
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GenerateSchedulesInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof generateSchedules>>
>;
export type GenerateSchedulesInfiniteQueryError = ErrorModel;

/**
 * @summary Generate Schedules
 */

export function createGenerateSchedulesInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof generateSchedules>>,
    GenerateSchedulesParams['offset']
  >,
  TError = ErrorModel
>(
  termID: () => number,
  generateSchedulesRequest: () => GenerateSchedulesRequest,
  params?: () => GenerateSchedulesParams,
  options?: () => {
    query?: Partial<
      CreateInfiniteQueryOptions<
        Awaited<ReturnType<typeof generateSchedules>>,
        TError,
        TData,
        QueryKey,
        GenerateSchedulesParams['offset']
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: () => QueryClient
): CreateInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const query = createInfiniteQuery(
    () =>
      useGenerateSchedulesInfiniteQueryOptions(
        termID(),
        generateSchedulesRequest(),
        params?.(),
        options?.()
      ),
    queryClient
  ) as CreateInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query;
}
