/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GatorPlanner API
 * OpenAPI spec version: 1.0.0
 */
import { createQuery } from '@tanstack/svelte-query';
import type {
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import type { ErrorModel, TypedListBuildingsRow } from '../../models';

import { customFetch } from '../../mutators/custom-fetch.ts';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getListBuildingsUrl = () => {
  return `/buildings`;
};

/**
 * Lists buildings in alphabetical order.
 * @summary List Buildings
 */
export const listBuildings = async (
  options?: Parameters<typeof customFetch>[1]
): Promise<TypedListBuildingsRow[]> => {
  return customFetch<TypedListBuildingsRow[]>(getListBuildingsUrl(), {
    ...options,
    method: 'GET'
  });
};

export const getListBuildingsQueryKey = () => {
  return [`/buildings`] as const;
};

export const getListBuildingsQueryOptions = <
  TData = Awaited<ReturnType<typeof listBuildings>>,
  TError = ErrorModel
>(options?: {
  query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof listBuildings>>, TError, TData>>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListBuildingsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listBuildings>>> = ({ signal }) =>
    listBuildings({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
    Awaited<ReturnType<typeof listBuildings>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListBuildingsQueryResult = NonNullable<Awaited<ReturnType<typeof listBuildings>>>;
export type ListBuildingsQueryError = ErrorModel;

/**
 * @summary List Buildings
 */

export function createListBuildings<
  TData = Awaited<ReturnType<typeof listBuildings>>,
  TError = ErrorModel
>(
  options?: () => {
    query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof listBuildings>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: () => QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const query = createQuery(
    () => getListBuildingsQueryOptions(options?.()),
    queryClient
  ) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query;
}

/**
 * @summary List Buildings
 */
export const prefetchListBuildingsQuery = async <
  TData = Awaited<ReturnType<typeof listBuildings>>,
  TError = ErrorModel
>(
  queryClient: QueryClient,
  options?: {
    query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof listBuildings>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  }
): Promise<QueryClient> => {
  const queryOptions = getListBuildingsQueryOptions(options);

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
};

export const getListDepartmentsUrl = () => {
  return `/departments`;
};

/**
 * Lists departments in alphabetical order.
 * @summary List Departments
 */
export const listDepartments = async (
  options?: Parameters<typeof customFetch>[1]
): Promise<string[]> => {
  return customFetch<string[]>(getListDepartmentsUrl(), {
    ...options,
    method: 'GET'
  });
};

export const getListDepartmentsQueryKey = () => {
  return [`/departments`] as const;
};

export const getListDepartmentsQueryOptions = <
  TData = Awaited<ReturnType<typeof listDepartments>>,
  TError = ErrorModel
>(options?: {
  query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof listDepartments>>, TError, TData>>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListDepartmentsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listDepartments>>> = ({ signal }) =>
    listDepartments({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
    Awaited<ReturnType<typeof listDepartments>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListDepartmentsQueryResult = NonNullable<Awaited<ReturnType<typeof listDepartments>>>;
export type ListDepartmentsQueryError = ErrorModel;

/**
 * @summary List Departments
 */

export function createListDepartments<
  TData = Awaited<ReturnType<typeof listDepartments>>,
  TError = ErrorModel
>(
  options?: () => {
    query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof listDepartments>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: () => QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const query = createQuery(
    () => getListDepartmentsQueryOptions(options?.()),
    queryClient
  ) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query;
}

/**
 * @summary List Departments
 */
export const prefetchListDepartmentsQuery = async <
  TData = Awaited<ReturnType<typeof listDepartments>>,
  TError = ErrorModel
>(
  queryClient: QueryClient,
  options?: {
    query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof listDepartments>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  }
): Promise<QueryClient> => {
  const queryOptions = getListDepartmentsQueryOptions(options);

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
};
